/**
 * Token format exporters — generate downloadable token files in
 * multiple formats from the active brand's DTCG JSON.
 *
 * Used by components/extensions/TokenExportDialog.
 */

import { buildSemanticPairs, buildBasePalette, getExtractionMeta } from "./loader";
import { currentBrand, brandLabel, type Brand } from "@/lib/brand";

export type ExportFormat = "json" | "css" | "swift" | "android-xml" | "kotlin";

const FORMAT_META: Record<
  ExportFormat,
  { label: string; ext: string; mime: string; description: string }
> = {
  json: {
    label: "JSON (W3C-DTCG)",
    ext: "json",
    mime: "application/json",
    description:
      "Standard W3C Design Tokens format. Tools: Style Dictionary, Tokens Studio, Theo.",
  },
  css: {
    label: "CSS custom properties",
    ext: "css",
    mime: "text/css",
    description:
      "Plain CSS variables. Drop-in for any web framework. Includes light/dark mode media queries.",
  },
  swift: {
    label: "Swift (UIKit + SwiftUI)",
    ext: "swift",
    mime: "text/x-swift",
    description: "iOS palette as Swift enum. Use Color(.tokenName) in SwiftUI.",
  },
  "android-xml": {
    label: "Android colors.xml",
    ext: "xml",
    mime: "application/xml",
    description:
      "Android resources XML. One color resource per semantic token (light); -night variant for dark.",
  },
  kotlin: {
    label: "Kotlin (Jetpack Compose)",
    ext: "kt",
    mime: "text/x-kotlin",
    description: "Compose Color objects, light/dark grouped.",
  },
};

export function exportFormats(): ExportFormat[] {
  return Object.keys(FORMAT_META) as ExportFormat[];
}

export function formatLabel(f: ExportFormat) {
  return FORMAT_META[f].label;
}
export function formatDescription(f: ExportFormat) {
  return FORMAT_META[f].description;
}

/** Returns { filename, mime, content } for the requested format. */
export function exportTokens(
  format: ExportFormat,
  brand: Brand = currentBrand(),
): { filename: string; mime: string; content: string } {
  const meta = FORMAT_META[format];
  const filename = `${brand}-tokens.${meta.ext}`;
  let content = "";

  const semantic = buildSemanticPairs(brand);
  const base = buildBasePalette(brand);
  const extractionMeta = getExtractionMeta(brand);

  switch (format) {
    case "json":
      content = JSON.stringify(
        {
          $schema: "https://design-tokens.github.io/community-group/format/",
          $description: `${brandLabel(brand)} design tokens. ${extractionMeta.observations} observations from ${extractionMeta.frames} frames.`,
          $extensions: { "indmoney-ds": extractionMeta },
          base: { colour: nestByPath(base.map((p) => [p.path, hexToColorObj(p.hex)])) },
          colour: nestByPath(
            semantic.flatMap((s) => [
              [s.path, hexToColorObj(s.light)],
              [s.path + "-dark", hexToColorObj(s.dark)],
            ]),
          ),
        },
        null,
        2,
      );
      break;

    case "css":
      content = renderCSS(brand, base, semantic);
      break;

    case "swift":
      content = renderSwift(brand, semantic);
      break;

    case "android-xml":
      content = renderAndroidXML(brand, semantic);
      break;

    case "kotlin":
      content = renderKotlin(brand, semantic);
      break;
  }

  return { filename, mime: meta.mime, content };
}

/** Trigger a browser download of the exported content. */
export function downloadTokens(format: ExportFormat, brand: Brand = currentBrand()) {
  const { filename, mime, content } = exportTokens(format, brand);
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  setTimeout(() => {
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, 100);
}

/* ─── Renderers ─────────────────────────────────────────────────────────────── */

function renderCSS(
  brand: Brand,
  base: ReturnType<typeof buildBasePalette>,
  semantic: ReturnType<typeof buildSemanticPairs>,
): string {
  const lines: string[] = [
    `/**`,
    ` * ${brandLabel(brand)} design tokens · CSS custom properties`,
    ` * Generated by INDmoney DS docs site. Do not edit by hand.`,
    ` */`,
    "",
    `:root, [data-theme="light"] {`,
  ];
  for (const p of base) {
    lines.push(`  --${cssVar(p.path)}: ${p.hex};`);
  }
  for (const s of semantic) {
    lines.push(`  --${cssVar(s.path)}: ${s.light};`);
  }
  lines.push("}");
  lines.push("");
  lines.push(`@media (prefers-color-scheme: dark) {`);
  lines.push(`  :root:not([data-theme="light"]) {`);
  for (const s of semantic) {
    lines.push(`    --${cssVar(s.path)}: ${s.dark};`);
  }
  lines.push(`  }`);
  lines.push(`}`);
  lines.push(`[data-theme="dark"] {`);
  for (const s of semantic) {
    lines.push(`  --${cssVar(s.path)}: ${s.dark};`);
  }
  lines.push(`}`);
  return lines.join("\n");
}

function renderSwift(
  brand: Brand,
  semantic: ReturnType<typeof buildSemanticPairs>,
): string {
  const lines: string[] = [
    `// ${brandLabel(brand)} design tokens — Swift (UIKit + SwiftUI)`,
    `// Generated by INDmoney DS docs site. Do not edit by hand.`,
    `import SwiftUI`,
    `import UIKit`,
    "",
    `enum ${swiftIdent(brand)}Tokens {`,
  ];
  for (const s of semantic) {
    const ident = swiftIdent(s.path);
    const lightUI = uiColorForHex(s.light);
    const darkUI = uiColorForHex(s.dark);
    lines.push(`  /** ${s.path} */`);
    lines.push(`  static let ${ident} = UIColor { trait in`);
    lines.push(`    trait.userInterfaceStyle == .dark ? ${darkUI} : ${lightUI}`);
    lines.push(`  }`);
    lines.push(`  static let ${ident}Color = Color(${ident})`);
    lines.push("");
  }
  lines.push("}");
  return lines.join("\n");
}

function renderAndroidXML(
  brand: Brand,
  semantic: ReturnType<typeof buildSemanticPairs>,
): string {
  const lines: string[] = [
    `<!--`,
    `  ${brandLabel(brand)} design tokens — Android colors.xml`,
    `  Generated by INDmoney DS docs site. Do not edit by hand.`,
    `  Place light values in res/values/colors.xml,`,
    `  dark values in res/values-night/colors.xml.`,
    `-->`,
    `<resources>`,
  ];
  for (const s of semantic) {
    const name = androidIdent(s.path);
    lines.push(`  <color name="${name}">${s.light}</color>`);
  }
  lines.push(`</resources>`);
  lines.push("");
  lines.push(`<!-- res/values-night/colors.xml -->`);
  lines.push(`<resources>`);
  for (const s of semantic) {
    const name = androidIdent(s.path);
    lines.push(`  <color name="${name}">${s.dark}</color>`);
  }
  lines.push(`</resources>`);
  return lines.join("\n");
}

function renderKotlin(
  brand: Brand,
  semantic: ReturnType<typeof buildSemanticPairs>,
): string {
  const lines: string[] = [
    `// ${brandLabel(brand)} design tokens — Jetpack Compose`,
    `// Generated by INDmoney DS docs site. Do not edit by hand.`,
    `package com.indmoney.designsystem.tokens`,
    "",
    `import androidx.compose.ui.graphics.Color`,
    "",
    `object ${swiftIdent(brand)}TokensLight {`,
  ];
  for (const s of semantic) {
    const ident = kotlinIdent(s.path);
    lines.push(`  val ${ident} = Color(0xFF${s.light.replace("#", "").toUpperCase()})`);
  }
  lines.push(`}`);
  lines.push("");
  lines.push(`object ${swiftIdent(brand)}TokensDark {`);
  for (const s of semantic) {
    const ident = kotlinIdent(s.path);
    lines.push(`  val ${ident} = Color(0xFF${s.dark.replace("#", "").toUpperCase()})`);
  }
  lines.push(`}`);
  return lines.join("\n");
}

/* ─── Helpers ───────────────────────────────────────────────────────────────── */

function cssVar(path: string): string {
  return path.replace(/[^a-z0-9-]+/gi, "-").replace(/-+/g, "-").toLowerCase();
}

function swiftIdent(s: string): string {
  return s
    .replace(/[^a-z0-9]+/gi, " ")
    .trim()
    .split(" ")
    .map((w, i) =>
      i === 0
        ? w.charAt(0).toLowerCase() + w.slice(1)
        : w.charAt(0).toUpperCase() + w.slice(1),
    )
    .join("");
}

function kotlinIdent(s: string): string {
  return swiftIdent(s);
}

function androidIdent(s: string): string {
  return s.replace(/[^a-z0-9]+/gi, "_").toLowerCase();
}

function uiColorForHex(hex: string): string {
  const h = hex.replace("#", "").slice(0, 6);
  const r = parseInt(h.slice(0, 2), 16) / 255;
  const g = parseInt(h.slice(2, 4), 16) / 255;
  const b = parseInt(h.slice(4, 6), 16) / 255;
  return `UIColor(red: ${r.toFixed(4)}, green: ${g.toFixed(4)}, blue: ${b.toFixed(4)}, alpha: 1)`;
}

function hexToColorObj(hex: string) {
  const h = hex.replace("#", "").slice(0, 6);
  const r = parseInt(h.slice(0, 2), 16) / 255;
  const g = parseInt(h.slice(2, 4), 16) / 255;
  const b = parseInt(h.slice(4, 6), 16) / 255;
  return {
    $type: "color",
    $value: { colorSpace: "srgb", components: [round(r), round(g), round(b)] },
  };
}

function round(x: number) {
  return Math.round(x * 10000) / 10000;
}

function nestByPath(entries: Iterable<[string, unknown]>) {
  const root: Record<string, unknown> = {};
  for (const [path, val] of entries) {
    const segs = path.split(".");
    let cursor: Record<string, unknown> = root;
    for (let i = 0; i < segs.length - 1; i++) {
      const seg = segs[i];
      if (!cursor[seg] || typeof cursor[seg] !== "object") cursor[seg] = {};
      cursor = cursor[seg] as Record<string, unknown>;
    }
    cursor[segs.at(-1)!] = val;
  }
  return root;
}
