/**
 * Icons manifest loader — reads public/icons/glyph/manifest.json at build time.
 *
 * The manifest is generated by `services/ds-service/cmd/icons` running the
 * Glyph icons extractor. Each icon has been post-processed to use
 * `currentColor` for fill + stroke so designers can recolor through CSS.
 */

import manifestData from "../../public/icons/glyph/manifest.json";

export type IconCategory = string;

export interface IconEntry {
  slug: string;
  name: string;
  category: IconCategory;
  set_id: string;
  variant_id: string;
  file: string; // e.g. "download-cloud.svg"
  width: number;
  height: number;
}

export interface IconManifest {
  generated_at: string;
  file_key: string;
  page_node_id: string;
  icons: IconEntry[];
  categories: IconCategory[];
}

const MANIFEST = manifestData as IconManifest;

export function allIcons(): IconEntry[] {
  return MANIFEST.icons;
}

export function iconCategories(): IconCategory[] {
  return MANIFEST.categories;
}

export function iconCount(): number {
  return MANIFEST.icons.length;
}

export function iconURL(icon: IconEntry): string {
  return `/icons/glyph/${icon.file}`;
}

export function searchIcons(query: string, limit = 100): IconEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return MANIFEST.icons.slice(0, limit);
  return MANIFEST.icons
    .filter((i) => i.name.toLowerCase().includes(q) || i.slug.includes(q))
    .slice(0, limit);
}
