/**
 * Icons manifest loader — reads public/icons/glyph/manifest.json at build time.
 *
 * The manifest is generated by `services/ds-service/cmd/icons` running the
 * Glyph icons extractor. Each icon has been post-processed to use
 * `currentColor` for fill + stroke so designers can recolor through CSS.
 */

import manifestData from "../../public/icons/glyph/manifest.json";

export type IconCategory = string;

/* ── Rich-extraction types ────────────────────────────────────────────────
 * Mirror Go structs in services/ds-service/cmd/variants/types.go. Every
 * field here is optional because:
 *   1. Old manifests produced before the rich-extraction phase don't
 *      carry these fields.
 *   2. Some components have no description / no doc_links / no variant
 *      axes (e.g. single-variant utility components) — they keep the
 *      legacy shape.
 * Consumers should treat absence as "no data captured" not "intentionally
 * empty"; render an empty state rather than a zero-value badge.
 */

export interface ComponentProperty {
  /** Full name with #N:M suffix preserved for non-VARIANT types. */
  name: string;
  type: "VARIANT" | "BOOLEAN" | "TEXT" | "INSTANCE_SWAP";
  default_value?: string | boolean | number | null;
  variant_options?: string[];
  preferred_values?: { type: string; key: string }[];
}

export interface VariantAxis {
  name: string;
  values: string[];
  default?: string;
}

export interface LayoutInfo {
  mode?: "HORIZONTAL" | "VERTICAL" | "NONE";
  wrap?: "NO_WRAP" | "WRAP";
  padding_left?: number;
  padding_right?: number;
  padding_top?: number;
  padding_bottom?: number;
  item_spacing?: number;
  counter_axis_spacing?: number;
  primary_align?: "MIN" | "CENTER" | "MAX" | "SPACE_BETWEEN";
  counter_align?: "MIN" | "CENTER" | "MAX" | "BASELINE";
  primary_sizing?: "FIXED" | "AUTO" | "HUG" | "FILL";
  counter_sizing?: "FIXED" | "AUTO" | "HUG" | "FILL";
  clips_content?: boolean;
  min_width?: number;
  max_width?: number;
  min_height?: number;
  max_height?: number;
}

export interface FillInfo {
  type: string;
  color?: string;
  opacity?: number;
  visible: boolean;
  blend_mode?: string;
  bound_variable_id?: string;
}

export interface EffectInfo {
  type: "DROP_SHADOW" | "INNER_SHADOW" | "LAYER_BLUR" | "BACKGROUND_BLUR" | string;
  radius?: number;
  spread?: number;
  offset_x?: number;
  offset_y?: number;
  color?: string;
  visible: boolean;
  bound_variable_id?: string;
}

export interface CornerInfo {
  uniform?: number;
  individual?: number[];
  smoothing?: number;
  bound_variable_id?: string;
}

export interface ChildSummary {
  id: string;
  type: string;
  name: string;
  component_id?: string;
  characters?: string;
  property_refs?: Record<string, string>;
  bound_variables?: Record<string, string>;
  width?: number;
  height?: number;
}

export interface CompositionRef {
  /** What the parent calls this slot ("Trailing Icon", "Action Bar_2CTA"). */
  instance_name: string;
  /** Figma node id this INSTANCE points at — COMPONENT or COMPONENT_SET. */
  component_id: string;
  /** "/"-joined ancestor name path from variant root down to this instance. */
  path?: string;
  /** Resolved atom slug if the componentId matches an extracted entry. */
  atom_slug?: string;
  /** Resolved tier of the embedded component (atom / molecule / parent). */
  resolved_tier?: "atom" | "molecule" | "parent";
  /** Resolved display name — saves a manifest lookup at render time. */
  resolved_name?: string;
}

export interface VariantEntry {
  /** Original Figma variant name, e.g. "State=Default, Size=Medium". */
  name: string;
  /** Parsed variable=value chips, in original order (legacy). */
  properties: Array<{ name: string; value: string }>;
  variant_id: string;
  file: string;
  width: number;
  height: number;

  /* Rich fields (Phase A extraction) — absent on legacy manifests. */
  key?: string;
  axis_values?: Record<string, string>;
  is_default?: boolean;
  layout?: LayoutInfo;
  fills?: FillInfo[];
  strokes?: FillInfo[];
  stroke_weight?: number;
  effects?: EffectInfo[];
  corner?: CornerInfo;
  opacity?: number;
  bound_variables?: Record<string, string>;
  children?: ChildSummary[];
  /** INSTANCEs in this variant's tree, with atom resolution. Parents only. */
  composes?: CompositionRef[];
}

export type ComponentTier = "atom" | "molecule" | "parent";

export interface IconEntry {
  slug: string;
  name: string;
  /** Populated by the Go extractor; absent on legacy manifests. */
  kind?: AssetKind;
  category: IconCategory;
  source?: string; // "atoms" | "icons-fresh" | etc
  set_id: string;
  variant_id: string;
  file: string;
  width: number;
  height: number;
  variants?: VariantEntry[];

  /* Rich fields (Phase A extraction). */
  key?: string;
  description?: string;
  doc_links?: string[];
  prop_defs?: ComponentProperty[];
  variant_axes?: VariantAxis[];
  single_variant_set?: boolean;

  /* Atomic-design tier classification (plan-002 Phase G). */
  tier?: ComponentTier;
  page?: string;     // human-readable page name ("Design System 🌟", "Atoms ")
  page_id?: string;  // Figma node id of the page
}

/** What an entry actually represents — derived from category + dimensions. */
export type AssetKind = "icon" | "component" | "illustration" | "logo";

// Legacy classifiers — used only when an entry lacks `kind` (manifests
// produced before the Go extractor learned to emit it). New extractions are
// fully data-driven and don't read these sets.
const LEGACY_LOGO_CATEGORIES = new Set(["Logo", "Logos", "bank", "nvidia", "merchant"]);
const LEGACY_ILLUSTRATION_CATEGORIES = new Set([
  "2D", "3D", "Profilecard", "Wallet", "Cold", "Masthead",
]);
const LEGACY_ICON_CATEGORIES = new Set(["Icon", "Filled Icons"]);

/**
 * Classify a manifest entry. The Atoms-page extractor walks every
 * COMPONENT_SET, so the manifest is a mix of icons, illustrations, brand
 * logos, and large component primitives (CTAs, progress bars, status bars).
 *
 * Heuristics:
 *   - Bank/brand collections → logo
 *   - 2D/3D/Profilecard/Wallet → illustration
 *   - Icon / Filled Icons → icon
 *   - "ui" category → wide assets (>=80px wide AND >=32px tall, or aspect>2)
 *     are components; tiny ones fall back to icon.
 *   - Tiny squares ≤32×32 default to icon, larger to illustration.
 */
export function classifyAsset(entry: IconEntry): AssetKind {
  // The extractor stamps `kind` directly. New manifests use this branch only.
  if (entry.kind) return entry.kind;

  // ── Legacy fallback: classify on the fly for manifests produced before
  // the extractor was kind-aware. Will be retired once a fresh sync runs.
  if (LEGACY_LOGO_CATEGORIES.has(entry.category)) return "logo";
  if (LEGACY_ILLUSTRATION_CATEGORIES.has(entry.category)) return "illustration";
  if (LEGACY_ICON_CATEGORIES.has(entry.category)) {
    const lower = entry.name.toLowerCase();
    if (lower.startsWith("3d ") || lower.startsWith("3d·") || lower.startsWith("3d ·")) {
      return "illustration";
    }
    return "icon";
  }
  const isWide = entry.width >= 80 && entry.height >= 28;
  const isLandscape = entry.width / Math.max(entry.height, 1) > 2;
  const isTinySquare = entry.width <= 32 && entry.height <= 32;
  if (entry.category === "ui") {
    return isWide || isLandscape ? "component" : "icon";
  }
  return isTinySquare ? "icon" : "illustration";
}

export function iconsByKind(kind: AssetKind): IconEntry[] {
  return MANIFEST.icons
    .filter((i) => classifyAsset(i) === kind)
    .sort((a, b) => a.name.localeCompare(b.name));
}

/** kebab-cased anchor slug for a category — used as section id + nav href. */
export function slugifyCategory(c: IconCategory): string {
  return (c || "uncategorized")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "") || "uncategorized";
}

/**
 * Audit C14: per-slug manual category override. The Figma extractor lands
 * a handful of named product icons (instacash, alpca, coin-swap, …) under
 * "uncategorized" because the source frame in Figma sits on the Icons
 * Fresh page without a category sub-frame. Until the source is reorganised,
 * remap them at consumer-time so they bin into a meaningful "Products"
 * section in the sidebar instead of getting buried in the OTHER pile.
 *
 * Add new slugs here as the team identifies more product icons that drift
 * into uncategorized. Keep the list short and curated — bulk re-categorisation
 * belongs upstream in the Figma file itself.
 */
const KNOWN_PRODUCT_CATEGORY_OVERRIDES: Record<string, string> = {
  instacash: "Products",
  alpca: "Products",
  "coin-swap": "Products",
  "coinswap": "Products",
};

/** Resolve the effective category for an entry, applying audit C14 overrides. */
function effectiveCategory(entry: IconEntry): IconCategory {
  const override = KNOWN_PRODUCT_CATEGORY_OVERRIDES[entry.slug];
  if (override) return override;
  return entry.category || "uncategorized";
}

/**
 * Audit C3: title-case the prettiest representation of a category whose
 * raw string was inconsistently cased / whitespaced in Figma. Used by
 * the dedupe pass below so the sidebar shows "Logos" + "Bank" instead
 * of "Logo" + "Logos" + "logos" + lowercase "bank".
 */
function prettifyCategory(raw: string): string {
  const trimmed = raw.trim();
  if (!trimmed) return "Uncategorized";
  // Preserve all-caps acronyms ("UI", "NVIDIA") — only re-case mixed/lower.
  if (trimmed === trimmed.toUpperCase() && trimmed.length <= 6) return trimmed;
  return trimmed
    .split(/\s+/)
    .map((w) => (w.length === 0 ? w : w[0].toUpperCase() + w.slice(1).toLowerCase()))
    .join(" ");
}

// Audit C25 — categories with fewer than this many entries are folded into
// "Other" instead of cluttering the sidebar with one-off taxonomy leftovers
// (Cold, Footer, Toast Messages, Primary Title, etc.). Tunable; 3 picks up
// genuine micro-categories without surfacing every typo.
const MIN_CATEGORY_SIZE = 3;

export function iconsByCategory(kind?: AssetKind): Map<IconCategory, IconEntry[]> {
  // Audit C3: group by a normalized key (trim + lowercase) so categories
  // that drift across designer files ("Logo" vs "Logos" vs "logo") collapse
  // into a single sidebar entry. The display label is derived from the first
  // raw category seen, prettified to title-case so the rendered nav reads
  // cleanly without mutating the manifest itself.
  const grouped = new Map<string, { display: IconCategory; entries: IconEntry[] }>();
  const pool = kind ? iconsByKind(kind) : MANIFEST.icons;
  for (const icon of pool) {
    // Audit C14: route product icons (instacash/alpca/coin-swap/...) into
    // "Products" instead of letting them sink into "uncategorized" / OTHER.
    const raw = effectiveCategory(icon);
    const key = raw.trim().toLowerCase() || "uncategorized";
    let bucket = grouped.get(key);
    if (!bucket) {
      bucket = { display: prettifyCategory(raw), entries: [] };
      grouped.set(key, bucket);
    }
    bucket.entries.push(icon);
  }
  // Audit C25 — fold tiny categories into "Other" so the sidebar isn't
  // dominated by single-entry leftovers. Skip the fold for the kind-filtered
  // mode where a small category may genuinely be the only one.
  const otherBucket: IconEntry[] = [];
  const out = new Map<IconCategory, IconEntry[]>();
  for (const { display, entries } of grouped.values()) {
    entries.sort((a, b) => a.name.localeCompare(b.name));
    if (!kind && entries.length < MIN_CATEGORY_SIZE) {
      otherBucket.push(...entries);
    } else {
      out.set(display, entries);
    }
  }
  if (otherBucket.length > 0) {
    otherBucket.sort((a, b) => a.name.localeCompare(b.name));
    const existing = out.get("Other") ?? [];
    out.set("Other", [...existing, ...otherBucket]);
  }
  return out;
}

export interface IconManifest {
  generated_at: string;
  file_key: string;
  page_node_id: string;
  icons: IconEntry[];
  categories: IconCategory[];
}

const MANIFEST = manifestData as IconManifest;

export function allIcons(): IconEntry[] {
  return MANIFEST.icons;
}

export function iconCategories(): IconCategory[] {
  return MANIFEST.categories;
}

export function iconCount(): number {
  return MANIFEST.icons.length;
}

export function iconURL(icon: IconEntry): string {
  return `/icons/glyph/${icon.file}`;
}

export function searchIcons(query: string, limit = 100): IconEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return MANIFEST.icons.slice(0, limit);
  return MANIFEST.icons
    .filter((i) => i.name.toLowerCase().includes(q) || i.slug.includes(q))
    .slice(0, limit);
}

/* ── Rich-data helpers ──────────────────────────────────────────────────
 * Used by the new component detail pages (`/components/[slug]`), the
 * health dashboard (`/health`), and the inspector enrichments. All
 * defensive: missing fields yield empty results rather than throw.
 */

/** Find a single component by slug — used by /components/[slug]. */
export function componentBySlug(slug: string): IconEntry | null {
  return MANIFEST.icons.find(
    (i) => i.slug === slug && (i.kind === "component" || (!i.kind && classifyAsset(i) === "component")),
  ) ?? null;
}

/**
 * Find a component by its durable Component.Key (the published-library
 * identifier from /v1/files/:key/component_sets). Returns null when no
 * component carries that key — most useful as a cross-file lookup; consumers
 * wanting "any component with this slug" should prefer componentBySlug.
 */
export function componentByKey(key: string): IconEntry | null {
  if (!key) return null;
  return MANIFEST.icons.find((i) => i.key === key) ?? null;
}

/**
 * Flatten an entry's VARIANT properties into a row-of-axis structure
 * convenient for table rendering: each row carries the axis name, every
 * possible value, and which value is the default. Non-VARIANT properties
 * (BOOLEAN/TEXT/INSTANCE_SWAP) are returned separately so the consumer can
 * render them with the appropriate type tag.
 */
export interface AxisMatrix {
  axes: VariantAxis[];
  /** Non-VARIANT properties — BOOLEAN / TEXT / INSTANCE_SWAP. */
  scalars: ComponentProperty[];
}
export function axisMatrix(entry: IconEntry): AxisMatrix {
  const axes = entry.variant_axes ?? [];
  const scalars = (entry.prop_defs ?? []).filter((p) => p.type !== "VARIANT");
  return { axes, scalars };
}

/** All components that have rich data (prop_defs OR variant_axes captured). */
export function componentsWithRichData(): IconEntry[] {
  return MANIFEST.icons.filter(
    (i) =>
      (i.kind === "component" || (!i.kind && classifyAsset(i) === "component")) &&
      ((i.prop_defs && i.prop_defs.length > 0) || (i.variant_axes && i.variant_axes.length > 0)),
  );
}

/** Return the variant flagged is_default, or fall back to the first. */
export function defaultVariantOf(entry: IconEntry): VariantEntry | null {
  const vs = entry.variants ?? [];
  if (vs.length === 0) return null;
  return vs.find((v) => v.is_default) ?? vs[0];
}

/** Total count of variants across all components. */
export function totalVariantCount(): number {
  let n = 0;
  for (const i of MANIFEST.icons) n += i.variants?.length ?? 0;
  return n;
}

/** Aggregate: how many of each property type exist across all components. */
export function propTypeBreakdown(): { variant: number; boolean: number; text: number; instance_swap: number } {
  const out = { variant: 0, boolean: 0, text: 0, instance_swap: 0 };
  for (const i of componentsWithRichData()) {
    for (const p of i.prop_defs ?? []) {
      if (p.type === "VARIANT") out.variant++;
      else if (p.type === "BOOLEAN") out.boolean++;
      else if (p.type === "TEXT") out.text++;
      else if (p.type === "INSTANCE_SWAP") out.instance_swap++;
    }
  }
  return out;
}

/** Aggregate: how many fills across all variants are bound to a Variable. */
export function bindingCoverage(): { fillsBound: number; fillsTotal: number; effectsBound: number; effectsTotal: number } {
  let fillsBound = 0, fillsTotal = 0, effectsBound = 0, effectsTotal = 0;
  for (const i of MANIFEST.icons) {
    for (const v of i.variants ?? []) {
      for (const f of v.fills ?? []) {
        if (f.type !== "SOLID") continue;
        fillsTotal++;
        if (f.bound_variable_id) fillsBound++;
      }
      for (const e of v.effects ?? []) {
        effectsTotal++;
        if (e.bound_variable_id) effectsBound++;
      }
    }
  }
  return { fillsBound, fillsTotal, effectsBound, effectsTotal };
}

/** Find components grouped by their first VARIANT axis name — for nav. */
export function componentsByPrimaryAxis(): Map<string, IconEntry[]> {
  const map = new Map<string, IconEntry[]>();
  for (const i of componentsWithRichData()) {
    const axis = i.variant_axes?.[0]?.name ?? "(no axis)";
    if (!map.has(axis)) map.set(axis, []);
    map.get(axis)!.push(i);
  }
  return map;
}

/** Filter to only the parent-tier (organism) components. */
export function parentComponents(): IconEntry[] {
  return MANIFEST.icons
    .filter((i) => i.tier === "parent")
    .sort((a, b) => a.name.localeCompare(b.name));
}

/** Filter to only atom-tier components. */
export function atomComponents(): IconEntry[] {
  return MANIFEST.icons
    .filter((i) => i.tier === "atom")
    .sort((a, b) => a.name.localeCompare(b.name));
}

/** Filter to only molecule-tier components. */
export function moleculeComponents(): IconEntry[] {
  return MANIFEST.icons
    .filter((i) => i.tier === "molecule")
    .sort((a, b) => a.name.localeCompare(b.name));
}

/**
 * Resolve a CompositionRef to the full atom IconEntry it points at, by
 * looking up either the resolved atom_slug (preferred — set by the
 * extractor) or the raw component_id against any variant_id /set_id
 * we know about.
 */
export function resolveComposition(ref: CompositionRef): IconEntry | null {
  if (ref.atom_slug) {
    const e = MANIFEST.icons.find((i) => i.slug === ref.atom_slug);
    if (e) return e;
  }
  if (!ref.component_id) return null;
  return (
    MANIFEST.icons.find(
      (i) =>
        i.set_id === ref.component_id ||
        (i.variants ?? []).some((v) => v.variant_id === ref.component_id),
    ) ?? null
  );
}

/** Total components, variants, and bound-variable count — for /health. */
export function systemStats() {
  const components = MANIFEST.icons.filter(
    (i) => i.kind === "component" || (!i.kind && classifyAsset(i) === "component"),
  );
  const totalVariants = components.reduce((n, i) => n + (i.variants?.length ?? 0), 0);
  const withDescription = components.filter((i) => i.description && i.description.trim().length > 0).length;
  return {
    components: components.length,
    variants: totalVariants,
    components_with_props: componentsWithRichData().length,
    components_with_description: withDescription,
    icons: MANIFEST.icons.filter((i) => classifyAsset(i) === "icon").length,
    illustrations: MANIFEST.icons.filter((i) => classifyAsset(i) === "illustration").length,
    logos: MANIFEST.icons.filter((i) => classifyAsset(i) === "logo").length,
  };
}
